services:
  pustara:
    build:
      context: ./backend
      dockerfile: ../Dockerfile
    container_name: pustara-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - FIREBASE_PROJECT_ID=pustara-kw
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
    restart: always